version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: KellyWorld
    command: npm run dev
    restart: unless-stopped
    environment:
      token: ''
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 1020M
