version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Bot 
    command: yarn start
    restart: unless-stopped
    ports:
      - "7777:7777"
    volumes:
      - /root/config.yml:/config.yml
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M