version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: KellyWorld
    command: yarn start
    restart: unless-stopped
    environment:
      token: ''
      mongodb: ''
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 521M
