# this action deploys this repository to the ssh server that was configured for more information visit: https://github.com/marketplace/actions/ssh-action-deploy

name: 🐦 deploy 

on:
  push:
    branches: [ "KellyWorld" ]

jobs:
  build:
    name: 🕳️ Ubuntu...
    runs-on: ubuntu-latest
    steps:
      - name: 💞 Github actions...
        uses: actions/checkout@v3
      - name: ✨ creating the config...
        run: |
          cat >>./config.yml <<END
            ${{ secrets.config }}
          END
        shell: bash 
      - name: 🌈 Deploy with ssh...
        uses: sebastianjnuwu/ssh-action-deploy@action
        with:
          IP: ${{ secrets.IP }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          FOLDER: 'root/.deploy'
          RUN: "cd .deploy && docker-compose up --build -d"