# ESLint is a great tool to help us automate code standardization with it we can define standardization rules, find non-standard codes and fix them automatically...

name: 🐥 Eslint

on:
  push:
    branches: [ "KellyWorld" ]
  pull_request:
    branches: [ "KellyWorld" ]

jobs:
  eslint:
    name: 🏜️ Starting the action 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 👻 Install Node v19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: ✨ Install dependencies
        run: npm install
      - name: 🌈 Run ESLint
        run: yarn lint
